zuul:
  routes:
    product:
      path: /app-product/**
      serviceId: app-product
    inventory:
      path: /app-inventory/**
      serviceId: app-inventory
server:  port: 8762
spring:  application:    name: zuul-server